package com.dapeng

package object bean {

  case class TEventDetailSecond(id:String,
                                biz_sys:String,
                                terminal:String,
                                net_addr:String,
                                net_addr_spare1:String,
                                net_addr_spare2:String,
                                event_theme:String,
                                event_id:String,
                                event_time:java.sql.Timestamp,
                                event_subject:String,
                                event_subject_spare1:String,
                                event_subject_spare2:String,
                                event_target:String,
                                event_target_spare1:String,
                                event_target_spare2:String,
                                event_target_spare3:String,
                                event_target_spare4:String,
                                extend1:String,
                                extend2:String,
                                extend3:String,
                                extend4:String,
                                extend5:String,
                                create_time:java.sql.Timestamp,
                                update_time:java.sql.Timestamp,
                                target_content:String,
                                uuid:String,
                                user_source:String,
                                user_location:String,
                                page_url:String,
                                net_type:String,
                                phone_model:String,
                                page_id:String,
                                app_version:String,
                                extend6:String,
                                extend7:String,
                                referrer:String,
                                user_agent:String,
                                device_id:String,
                                download_channel:String)
}
